# Configuration for Sidekiq
#
# Options here can still be overridden by command-line args.
#    sidekiq -C path/to/config.yml
#
# Note: THIS FILE WILL ONLY APPLY FOR DEVELOPMENT AND TEST.
# Deployment recipes override this file, so if you make changes
# here and you need to see them in production or staging, you
# need to go change the recipe instead.
#
---
:verbose: false
:pidfile: ./tmp/pids/sidekiq.pid
:concurrency: 25
:queues:
  - [medulla, 16]
  - [nectarine, 8]
  - [default, 4]
  - [mailer, 2]
